#define IOCTL_START_NUM 0x80
#define IOCTL_NUM1 IOCTL_START_NUM+1
#define IOCTL_NUM2 IOCTL_START_NUM+2
#define IOCTL_NUM3 IOCTL_START_NUM+3
#define IOCTL_NUM4 IOCTL_START_NUM+4

#define KU_IOCTL_NUM 'z'
#define KU_IPC_MAXMSG 10 
#define KU_IPC_MAXVOL 128
#define KU_IPC_CREATE _IOWR(KU_IOCTL_NUM, IOCTL_NUM1, unsigned long)
#define KU_IPC_EXCL _IOWR(KU_IOCTL_NUM, IOCTL_NUM2, unsigned long)
#define KU_IPC_NOWAIT _IOWR(KU_IOCTL_NUM, IOCTL_NUM3, unsigned long)
#define KU_MSG_NOERROR _IOWR(KU_IOCTL_NUM, IOCTL_NUM4, unsigned long)
